Fix crash in VideoModule - Method called after release()
Completely eliminate the runtime exception caused by monkey.
Sample stack trace:
java.lang.RuntimeException: Method called after release()
       at android.media.MediaRecorder.setCamera(Native Method)
       at com.android.camera.VideoModule.initializeRecorder(VideoModule.java:1101)
       at com.android.camera.VideoModule.access$2000(VideoModule.java:88)
       at com.android.camera.VideoModule$10.onStorageUpdateDone(VideoModule.java:1320)
       at com.android.camera.CameraActivity$20.onPostExecute(CameraActivity.java:2014)

Bug: 17313985
Change-Id: I7ecaf375c26ebd1608d7098599ab1528609287ce